function [infostring]=subplotInfobox(trialTab,dayStruct,color,pooled,position,titlestring)
data=trialTab;
responseIdx=~isnan(data.ResponseCorrect);
catchIdx=data.CatchTrial==1;
if pooled
infostring{1}=sprintf('acc %2.0f%s bias %2.0f%s lapse %2.0f%s',...
        sum(data.ResponseCorrect(responseIdx))/sum(responseIdx)*100,'%',...
        sum(data.ResponseLeft(responseIdx))/sum(responseIdx)*100,'%',...
    dayStruct.error.all(1),'%');
infostring{2}=sprintf('%d trials %d sessions',...
    sum(responseIdx),...
    size(dayStruct.error.all,1));
else
infostring{1}=sprintf('n=%d reward %2.1fml coutEarly %1.0f%s',...
    sum(responseIdx),...
    sum(data.RewardReceivedTotal)/1000,...
    sum(data.CoutEarly)/length(data.CoutEarly)*100,'%');

infostring{2}=sprintf('acc %2.0f%s bias %2.0f%s lapse %2.0f%s',...
        sum(data.ResponseCorrect(responseIdx))/sum(responseIdx)*100,'%',...
        sum(data.ResponseLeft(responseIdx))/sum(responseIdx)*100,'%',...
    dayStruct.error.all(1),'%');


infostring{3}=sprintf('fbDelay %2.1fs (%2.1f-%2.1fs)',...   
    mean(data.FeedbackDelay(responseIdx&~catchIdx)),...
    min(data.FeedbackDelay(responseIdx&~catchIdx)),...
    max(data.FeedbackDelay(responseIdx&~catchIdx)));

infostring{4}=sprintf('skippedFb %1.0f%s (%1.0f%s/%1.0f%s)',... 
    sum(data.LoutEarly(data.ResponseCorrect==1))/sum(data.ResponseCorrect==1)*100,'%',...
    sum(data.LoutEarly(data.ResponseCorrect==1&data.ResponseLeft==1))/sum(data.ResponseCorrect==1&data.ResponseLeft==1)*100,'%',...
    sum(data.LoutEarly(data.ResponseCorrect==1&data.ResponseLeft==0))/sum(data.ResponseCorrect==1&data.ResponseLeft==0)*100,'%');
end

annotation('textbox',position,'FitBoxToText','on','String',infostring,'BackgroundColor',color.info,'LineStyle','none','Color','k','VerticalAlignment','middle','HorizontalAlignment','center');
title(titlestring)
axis off
